apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
spec:
  template:
    spec:
      initContainers:
      - name: init-storage
        image: busybox
        command: ["sh", "-c", "mkdir -p /storage/{app,framework,logs} && chown -R 33:33 /storage"]
        volumeMounts:
        - name: storage
          mountPath: /storage

      containers:
      - name: php-fpm
        image: cloudsihmar/tipl-php:v1
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: php-config
          mountPath: /usr/local/etc/php/conf.d/local.ini
          subPath: local.ini
        - name: storage
          mountPath: /var/www/storage
          subPath: storage
        - name: storage
          mountPath: /var/www/bootstrap/cache
          subPath: bootstrap-cache
      volumes:
      - name: php-config
        configMap:
          name: php-config
      - name: storage
        persistentVolumeClaim:
          claimName: tipl-storage-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: cloudsihmar/tipl-nginx:v2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf-d
          mountPath: /etc/nginx/conf.d/
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: storage
          mountPath: /var/www/public/storage
          subPath: storage/app/public
          readOnly: true
      volumes:
      - name: nginx-conf-d
        configMap:
          name: nginx-conf-d
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}
      - name: storage
        persistentVolumeClaim:
          claimName: tipl-storage-pvc
          readOnly: true
