apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
spec:
  selector:
    app: tipl
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: tipl
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
